origin: madoka.pink.
ttl: 60

soa:
  ns: pihole-01.madoka.pink.
  user: root.madoka.pink.

records:
  - type: NS
    value: pihole-01.madoka.pink.

  - type: A
    host: "@"
    value: 192.168.1.1

  - type: A
    host: pihole-01.madoka.pink.
    value: 192.168.1.20

  - type: A
    host: rpi3-01
    value: 192.168.1.20

  - type: A
    host: rpi4-01
    value: 192.168.1.21

  - type: A
    host: rpi4-02
    value: 192.168.1.22

  - type: A
    host: ilo4-01
    value: 192.168.1.11

  - type: A
    host: pve-01
    value: 192.168.1.30
